using System.Security.Cryptography;
using System.Text;
using System.Text.Json;

namespace Player.AudioSmoke;

internal static class WavFixture
{
    public static object Generate(string path)
    {
        path = Path.GetFullPath(path);
        var manifestPath = path + ".json";
        if (File.Exists(path) || File.Exists(manifestPath))
            throw new IOException("Fixture or manifest already exists; select a new output path.");
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        const int sampleRate = 48000;
        const int frames = 3 * sampleRate;
        const int dataBytes = frames * 2 * sizeof(short);
        using (var stream = new FileStream(path, FileMode.CreateNew, FileAccess.Write))
        using (var writer = new BinaryWriter(stream, Encoding.ASCII))
        {
            writer.Write("RIFF"u8); writer.Write(36 + dataBytes); writer.Write("WAVEfmt "u8);
            writer.Write(16); writer.Write((short)1); writer.Write((short)2);
            writer.Write(sampleRate); writer.Write(sampleRate * 4);
            writer.Write((short)4); writer.Write((short)16);
            writer.Write("data"u8); writer.Write(dataBytes);
            for (var i = 0; i < frames; i++)
            {
                var sample = (short)Math.Round(Math.Sin(2 * Math.PI * 440 * i / sampleRate) * 0.05 * short.MaxValue);
                writer.Write(sample); writer.Write((short)-sample);
            }
        }
        using var input = File.OpenRead(path);
        var fixture = new
        {
            SchemaVersion = 1, Path = Path.GetFileName(path), Container = "WAV", Codec = "PCM signed 16-bit LE",
            SampleRate = sampleRate, Channels = 2, DurationSeconds = 3, DurationToleranceSeconds = 0.001,
            PeakTolerance = 0.001, ExpectedPeak = 0.05,
            Sha256 = Convert.ToHexString(SHA256.HashData(input)).ToLowerInvariant(),
            Provenance = "Generated by Player.AudioSmoke.WavFixture; 440 Hz sine with opposite-phase channels",
            License = "CC0-1.0", IntendedChecks = new[] { "decode", "duration", "seek", "end-of-file", "shared output", "disposal" }
        };
        using var manifest = new FileStream(manifestPath, FileMode.CreateNew, FileAccess.Write);
        JsonSerializer.Serialize(manifest, fixture, new JsonSerializerOptions { WriteIndented = true });
        return fixture;
    }
}
