<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>14.0</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <BuildSequence Condition="'$(BuildSequence)' == '' and '$(GITHUB_RUN_NUMBER)' != ''">$(GITHUB_RUN_NUMBER)</BuildSequence>
    <BuildSequence Condition="'$(BuildSequence)' == ''">0</BuildSequence>
    <BuildAttempt Condition="'$(BuildAttempt)' == '' and '$(GITHUB_RUN_ATTEMPT)' != ''">$(GITHUB_RUN_ATTEMPT)</BuildAttempt>
    <BuildAttempt Condition="'$(BuildAttempt)' == ''">0</BuildAttempt>
    <ReleaseVersion Condition="'$(ReleaseVersion)' == ''">$(MPSWIFT_RELEASE_VERSION)</ReleaseVersion>
    <Version Condition="'$(ReleaseVersion)' == ''">1.0.$(BuildSequence)-dev.$(BuildAttempt)</Version>
    <Version Condition="'$(ReleaseVersion)' != ''">$(ReleaseVersion)+build.$(BuildSequence).$(BuildAttempt)</Version>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.$(BuildSequence).$(BuildAttempt)</FileVersion>
  </PropertyGroup>
</Project>
