<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <OutputType>WinExe</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishTrimmed>false</PublishTrimmed>
    <PublishSingleFile>false</PublishSingleFile>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Player.Core/Player.Core.csproj" />
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="ManagedBass" />
    <PackageReference Include="ManagedBass.Mix" />
    <PackageReference Include="ManagedBass.Wasapi" />
    <PackageReference Include="TagLibSharp" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <Content Include="../../native/manifest.json" Link="native/manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../native/win-x64/**/*.txt" Link="native/win-x64/%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="../../native/win-x64/*.dll" Link="native/win-x64/%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
