; Compile only the audited payload generated by Package-Installer.ps1.
#ifndef PayloadDirectory
  #error PayloadDirectory is required
#endif
[Setup]
AppId={{EC91F463-A93D-4DBE-94B7-2199F2F64FA6}
AppName=MPswift
AppVersion={#ProductVersion}
AppPublisher=MPswift
AppPublisherURL=https://github.com/kurasis/MPswift
AppSupportURL=https://github.com/kurasis/MPswift/issues
DefaultDirName={localappdata}\Programs\MPswift
DefaultGroupName=MPswift
DisableProgramGroupPage=yes
PrivilegesRequired=lowest
ArchitecturesAllowed=x64os
ArchitecturesInstallIn64BitMode=x64os
MinVersion=10.0.19041
OutputDir={#OutputDirectory}
OutputBaseFilename={#OutputName}
SetupIconFile={#AppIcon}
UninstallDisplayIcon={app}\MPswift.exe
VersionInfoVersion={#FileVersion}
VersionInfoProductVersion={#FileVersion}
Compression=lzma2
SolidCompression=yes
WizardStyle=modern
CloseApplications=yes
CloseApplicationsFilter=MPswift.exe
RestartApplications=no
Uninstallable=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
#include "payload-files.iss"

[Icons]
Name: "{userprograms}\{groupname}\MPswift"; Filename: "{app}\MPswift.exe"; WorkingDir: "{app}"
Name: "{userprograms}\{groupname}\{cm:UninstallProgram,MPswift}"; Filename: "{uninstallexe}"
Name: "{userdesktop}\MPswift"; Filename: "{app}\MPswift.exe"; WorkingDir: "{app}"; Tasks: desktopicon

[Run]
Filename: "{app}\MPswift.exe"; Description: "{cm:LaunchProgram,MPswift}"; Flags: nowait postinstall skipifsilent unchecked

[CustomMessages]
english.PortableDirectory=Choose a separate installation folder. Keep your portable Data folder and use the player backup/restore commands to migrate it.
russian.PortableDirectory=Выберите отдельную папку установки. Сохраните переносимую папку Data и используйте резервное копирование и восстановление в плеере для переноса данных.
english.ForeignDirectory=Choose an empty folder or an existing MPswift installation. Unrelated files will not be overwritten.
russian.ForeignDirectory=Выберите пустую папку или существующую установку MPswift. Посторонние файлы не будут перезаписаны.

[Code]
function PrepareToInstall(var NeedsRestart: Boolean): String;
var
  Directory: String;
  Marker: AnsiString;
  Entry: TFindRec;
begin
  Result := '';
  Directory := ExpandConstant('{app}');
  if FileExists(Directory + '\portable.marker') or DirExists(Directory + '\Data') then begin
    Result := CustomMessage('PortableDirectory');
    Exit;
  end;
  if DirExists(Directory) then begin
    if LoadStringFromFile(Directory + '\.mpswift-installation', Marker) and
      (Trim(String(Marker)) = 'MPswift EC91F463-A93D-4DBE-94B7-2199F2F64FA6') then Exit;
    if FindFirst(Directory + '\*', Entry) then begin
      try
        repeat
          if (Entry.Name <> '.') and (Entry.Name <> '..') then begin
            Result := CustomMessage('ForeignDirectory');
            Exit;
          end;
        until not FindNext(Entry);
      finally
        FindClose(Entry);
      end;
    end;
  end;
end;
